version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=crash
      - MONGO_PASSWORD=burn
      - SESSION_SECRET=victor
    command: npm run dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=crash
      - MONGO_INITDB_ROOT_PASSWORD=burn
     