version: "3"
services:
  node-app:
    build: .
    ports:
      - "3080:3080"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3080
    # env_file:
    #   - ./.env