version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=crash
      - MONGO_PASSWORD=burn
    command: npm run dev
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=crash
      - MONGO_INITDB_ROOT_PASSWORD=burn
     